-- 002: v2 data model.
--   * Jobs are made of line items (service, any number of add-ons, custom items). Each line freezes
--     its price/commission when added, so editing the Pricing Matrix never rewrites history.
--   * Vehicle classes and the catalog (services + add-ons) are data, not hardcoded columns.
--   * Owner/staff roles (app_users), automatic audit log of every change, voiding instead of
--     deleting jobs, day closing, unique JO numbers, real date/boolean/money types + constraints.
-- The pre-migration tables are copied to legacy_v1_* first, so nothing is lost.

-- ---------------------------------------------------------------- helpers

create or replace function public.set_updated_at() returns trigger language plpgsql as $$
begin
  if row(new.*) is distinct from row(old.*) then
    new.updated_at := now();
  end if;
  return new;
end $$;

create table public.audit_log (
  id bigint generated by default as identity primary key,
  at timestamptz not null default now(),
  actor text,
  table_name text not null,
  row_pk text,
  action text not null,
  old_row jsonb,
  new_row jsonb
);
create index audit_log_at_idx on public.audit_log (at desc);
create index audit_log_row_idx on public.audit_log (table_name, row_pk);

-- Generic row-change logger. TG_ARGV[0] names the primary-key column (default 'id').
-- The app sets app.actor (the signed-in email) at the start of each write transaction.
create or replace function public.audit_row() returns trigger language plpgsql as $$
declare
  pk_col text := coalesce(tg_argv[0], 'id');
  old_j jsonb := case when tg_op <> 'INSERT' then to_jsonb(old) end;
  new_j jsonb := case when tg_op <> 'DELETE' then to_jsonb(new) end;
begin
  if tg_op = 'UPDATE' and old_j = new_j then
    return null;
  end if;
  insert into public.audit_log (actor, table_name, row_pk, action, old_row, new_row)
  values (nullif(current_setting('app.actor', true), ''), tg_table_name,
          coalesce(new_j, old_j) ->> pk_col, tg_op, old_j, new_j);
  return null;
end $$;

-- ---------------------------------------------------------------- safety copies

create table public.legacy_v1_jobs as table public.jobs;
create table public.legacy_v1_services as table public.services;
create table public.legacy_v1_addons as table public.addons;
create table public.legacy_v1_payroll_entries as table public.payroll_entries;

-- ---------------------------------------------------------------- vehicle classes

create table public.vehicle_classes (
  code text primary key check (code ~ '^[A-Z0-9_]{1,16}$'),
  label text not null check (btrim(label) <> ''),
  sort_order integer not null default 0,
  active boolean not null default true
);
insert into public.vehicle_classes (code, label, sort_order) values
  ('S', 'S', 10), ('M', 'M', 20), ('L', 'L', 30), ('XL', 'XL', 40),
  ('MOTO', 'MOTO', 50), ('BIG_MOTO', 'BIG MOTO', 60);

update public.jobs set vehicle_class = null where btrim(vehicle_class) = '';
update public.jobs set vehicle_class = upper(btrim(vehicle_class)) where vehicle_class is not null;
-- Keep any class that exists in job history even if it is not in the default list.
insert into public.vehicle_classes (code, label, sort_order)
select distinct vehicle_class, vehicle_class, 100 from public.jobs
where vehicle_class is not null
  and vehicle_class not in (select code from public.vehicle_classes);

-- ---------------------------------------------------------------- catalog

create table public.catalog_items (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('service', 'addon')),
  name text not null check (btrim(name) <> ''),
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index catalog_items_active_name_key on public.catalog_items (kind, lower(name)) where active;

create table public.catalog_prices (
  item_id bigint not null references public.catalog_items (id) on delete cascade,
  vehicle_class text not null references public.vehicle_classes (code) on update cascade on delete cascade,
  price numeric(12,2) not null default 0 check (price >= 0),
  commission numeric(12,2) not null default 0 check (commission >= 0),
  primary key (item_id, vehicle_class)
);

-- The old CUSTOM pseudo-service becomes free-form custom line items instead.
insert into public.catalog_items (kind, name, sort_order, active)
select 'service', name, (row_number() over (order by id)) * 10, coalesce(active, 1) <> 0
from public.services where coalesce(is_custom, 0) = 0;

insert into public.catalog_items (kind, name, sort_order, active)
select 'addon', name, (row_number() over (order by id)) * 10, coalesce(active, 1) <> 0
from public.addons;

create temporary table _item_map on commit drop as
select 'service'::text as kind, s.id as old_id, ci.id as new_id, to_jsonb(s) as old_row
from public.services s join public.catalog_items ci on ci.kind = 'service' and ci.name = s.name
union all
select 'addon', a.id, ci.id, to_jsonb(a)
from public.addons a join public.catalog_items ci on ci.kind = 'addon' and ci.name = a.name;

insert into public.catalog_prices (item_id, vehicle_class, price, commission)
select m.new_id, vc.code,
       greatest(coalesce((m.old_row ->> ('price_' || vc.code))::numeric, 0), 0),
       greatest(coalesce((m.old_row ->> ('comm_' || vc.code))::numeric, 0), 0)
from _item_map m cross join public.vehicle_classes vc;

-- ---------------------------------------------------------------- job line items

create table public.job_items (
  id bigint generated by default as identity primary key,
  job_id bigint not null references public.jobs (id) on delete cascade,
  kind text not null check (kind in ('service', 'addon', 'custom')),
  catalog_item_id bigint references public.catalog_items (id) on delete set null,
  name text not null check (btrim(name) <> ''),
  price numeric(12,2) not null default 0 check (price >= 0),
  commission numeric(12,2) not null default 0 check (commission >= 0),
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);
create index job_items_job_id_idx on public.job_items (job_id);

-- Backfill: prices are taken from the matrix as it is today, which is what the old app was
-- displaying for these jobs anyway.
insert into public.job_items (job_id, kind, catalog_item_id, name, price, commission, sort_order)
select j.id, 'service', m.new_id, m.old_row ->> 'name',
       greatest(coalesce((m.old_row ->> ('price_' || j.vehicle_class))::numeric, 0), 0),
       greatest(coalesce((m.old_row ->> ('comm_' || j.vehicle_class))::numeric, 0), 0), 0
from public.jobs j join _item_map m on m.kind = 'service' and m.old_id = j.service_id;

insert into public.job_items (job_id, kind, catalog_item_id, name, price, commission, sort_order)
select j.id, 'addon', m.new_id, m.old_row ->> 'name',
       greatest(coalesce(j.addon_price_override, (m.old_row ->> ('price_' || j.vehicle_class))::numeric, 0), 0),
       greatest(coalesce((m.old_row ->> ('comm_' || j.vehicle_class))::numeric, 0), 0), 1
from public.jobs j join _item_map m on m.kind = 'addon' and m.old_id = j.addon_id;

insert into public.job_items (job_id, kind, name, price, commission, sort_order)
select j.id, 'custom', coalesce(nullif(btrim(j.custom_addon_name), ''), 'Custom item'),
       greatest(coalesce(j.custom_price, 0), 0), greatest(coalesce(j.custom_comm, 0), 0), 2
from public.jobs j
left join public.services s on s.id = j.service_id
where coalesce(j.custom_price, 0) <> 0 or coalesce(j.custom_comm, 0) <> 0
   or nullif(btrim(j.custom_addon_name), '') is not null or coalesce(s.is_custom, 0) <> 0;

-- ---------------------------------------------------------------- jobs

-- Duplicate JO numbers (the old COUNT+1 scheme reused numbers after deletes) get the next
-- free sequence number for their date.
with ranked as (
  select id, job_date, row_number() over (partition by jo_number order by id) as rn
  from public.jobs where jo_number is not null
), maxes as (
  select job_date, coalesce(max(substring(jo_number from '(\d+)$')::int), 0) as mx
  from public.jobs group by job_date
), renum as (
  select r.id,
         'JO-' || to_char(r.job_date::date, 'MMDDYY') || '-' ||
         lpad((m.mx + row_number() over (partition by r.job_date order by r.id))::text, 3, '0') as jo
  from ranked r join maxes m on m.job_date = r.job_date
  where r.rn > 1
)
update public.jobs j set jo_number = renum.jo from renum where j.id = renum.id;

update public.jobs set payment_method = 'Cash' where payment_method is null or btrim(payment_method) = '';
update public.jobs set payment_method = 'GCash' where lower(payment_method) = 'gcash';
update public.jobs set payment_method = 'Cash' where lower(payment_method) = 'cash';

alter table public.jobs
  drop column service_id,
  drop column addon_id,
  drop column addon_price_override,
  drop column custom_addon_name,
  drop column custom_price,
  drop column custom_comm,
  drop column commission_paid,
  drop column commission_payment_method,
  drop column commission_cash_paid,
  drop column commission_gcash_paid;

alter table public.jobs
  alter column job_date type date using job_date::date,
  alter column discount type numeric(12,2) using round(greatest(coalesce(discount, 0), 0), 2),
  alter column discount set default 0,
  alter column discount set not null,
  alter column tip_gcash type numeric(12,2) using round(greatest(coalesce(tip_gcash, 0), 0), 2),
  alter column tip_gcash set default 0,
  alter column tip_gcash set not null,
  alter column payment_method set default 'Cash',
  alter column payment_method set not null,
  alter column payment_received drop default,
  alter column payment_received type boolean using coalesce(payment_received, 0) <> 0,
  alter column payment_received set default false,
  alter column payment_received set not null,
  alter column created_at set default now(),
  add column created_by text default nullif(current_setting('app.actor', true), ''),
  add column updated_at timestamptz not null default now(),
  add column voided_at timestamptz,
  add column voided_by text,
  add column void_reason text,
  add constraint jobs_payment_method_check check (payment_method in ('Cash', 'GCash')),
  add constraint jobs_discount_check check (discount >= 0),
  add constraint jobs_tip_gcash_check check (tip_gcash >= 0),
  add constraint jobs_vehicle_class_fkey foreign key (vehicle_class)
    references public.vehicle_classes (code) on update cascade;

create unique index jobs_jo_number_key on public.jobs (jo_number);

-- ---------------------------------------------------------------- expenses

alter table public.expenses
  alter column expense_date type date using expense_date::date,
  alter column side set not null,
  alter column amount type numeric(12,2) using round(coalesce(amount, 0), 2),
  alter column amount set default 0,
  alter column amount set not null,
  add column created_at timestamptz not null default now(),
  add column created_by text default nullif(current_setting('app.actor', true), ''),
  add constraint expenses_side_check check (side in ('cash', 'gcash')),
  add constraint expenses_amount_check check (amount >= 0);

-- ---------------------------------------------------------------- daily_meta (one row per business day)

alter table public.daily_meta
  alter column job_date type date using job_date::date,
  alter column cash_float type numeric(12,2) using round(coalesce(cash_float, 0), 2),
  alter column cash_float set default 0,
  alter column cash_float set not null,
  alter column actual_cash type numeric(12,2),
  alter column actual_gcash type numeric(12,2),
  alter column gcash_tips_to_distribute type numeric(12,2) using round(coalesce(gcash_tips_to_distribute, 0), 2),
  alter column gcash_tips_to_distribute set default 0,
  alter column gcash_tips_to_distribute set not null,
  alter column commission_gcash_paid type numeric(12,2) using round(coalesce(commission_gcash_paid, 0), 2),
  alter column commission_gcash_paid set default 0,
  alter column commission_gcash_paid set not null,
  add column closed_at timestamptz,
  add column closed_by text,
  add column updated_at timestamptz not null default now(),
  add constraint daily_meta_money_check check (
    cash_float >= 0 and gcash_tips_to_distribute >= 0 and commission_gcash_paid >= 0);

-- ---------------------------------------------------------------- employees + payroll

alter table public.employees
  alter column role set default '',
  alter column rate_per_day type numeric(12,2) using round(coalesce(rate_per_day, 0), 2),
  alter column rate_per_day set default 0,
  alter column rate_per_day set not null,
  alter column construction_rate type numeric(12,2) using round(coalesce(construction_rate, 0), 2),
  alter column construction_rate set default 0,
  alter column construction_rate set not null,
  alter column active drop default,
  alter column active type boolean using coalesce(active, 1) <> 0,
  alter column active set default true,
  alter column active set not null,
  add column updated_at timestamptz not null default now(),
  add constraint employees_rates_check check (rate_per_day >= 0 and construction_rate >= 0);

-- Overtime used to live in ot_hours before the carwash/construction split.
update public.payroll_entries set cw_ot_hours = ot_hours
where coalesce(cw_ot_hours, 0) = 0 and coalesce(ot_hours, 0) <> 0;

alter table public.payroll_entries rename column period_label to period_start;

-- Day totals are always recomputed from attendance, so the stored copies are dropped.
-- Rates are now frozen per week so changing an employee's rate does not rewrite old payroll.
alter table public.payroll_entries
  drop column days_worked,
  drop column half_days,
  drop column absences,
  drop column day_off,
  drop column ot_hours,
  drop column construction_days,
  alter column period_start type date using date_trunc('week', period_start::date)::date,
  alter column attendance drop default,
  alter column attendance type jsonb using coalesce(nullif(btrim(attendance), ''), '{}')::jsonb,
  alter column attendance set default '{}'::jsonb,
  alter column attendance set not null,
  alter column cw_ot_hours type numeric(6,2) using coalesce(cw_ot_hours, 0),
  alter column cw_ot_hours set default 0,
  alter column cw_ot_hours set not null,
  alter column cn_ot_hours type numeric(6,2) using coalesce(cn_ot_hours, 0),
  alter column cn_ot_hours set default 0,
  alter column cn_ot_hours set not null,
  alter column deductions type numeric(12,2) using round(coalesce(deductions, 0), 2),
  alter column deductions set default 0,
  alter column deductions set not null,
  add column rate_per_day numeric(12,2),
  add column construction_rate numeric(12,2),
  add column updated_at timestamptz not null default now();

update public.payroll_entries p
set rate_per_day = e.rate_per_day, construction_rate = e.construction_rate
from public.employees e where e.id = p.employee_id;

alter table public.payroll_entries
  alter column rate_per_day set not null,
  alter column construction_rate set not null,
  add constraint payroll_entries_values_check check (
    extract(isodow from period_start) = 1 and jsonb_typeof(attendance) = 'object'
    and rate_per_day >= 0 and construction_rate >= 0
    and cw_ot_hours >= 0 and cn_ot_hours >= 0 and deductions >= 0);

-- ---------------------------------------------------------------- app users / roles

create table public.app_users (
  email text primary key check (email = lower(btrim(email)) and email like '%@%'),
  user_id uuid unique,
  role text not null check (role in ('owner', 'staff')),
  display_name text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------- retire the wide pricing tables

drop table public.services;
drop table public.addons;

-- ---------------------------------------------------------------- triggers, RLS

create trigger set_updated_at before update on public.jobs for each row execute function public.set_updated_at();
create trigger set_updated_at before update on public.catalog_items for each row execute function public.set_updated_at();
create trigger set_updated_at before update on public.daily_meta for each row execute function public.set_updated_at();
create trigger set_updated_at before update on public.employees for each row execute function public.set_updated_at();
create trigger set_updated_at before update on public.payroll_entries for each row execute function public.set_updated_at();
create trigger set_updated_at before update on public.app_users for each row execute function public.set_updated_at();

create trigger audit after insert or update or delete on public.jobs for each row execute function public.audit_row();
create trigger audit after insert or update or delete on public.job_items for each row execute function public.audit_row();
create trigger audit after insert or update or delete on public.expenses for each row execute function public.audit_row();
create trigger audit after insert or update or delete on public.daily_meta for each row execute function public.audit_row('job_date');
create trigger audit after insert or update or delete on public.catalog_items for each row execute function public.audit_row();
create trigger audit after insert or update or delete on public.catalog_prices for each row execute function public.audit_row('item_id');
create trigger audit after insert or update or delete on public.vehicle_classes for each row execute function public.audit_row('code');
create trigger audit after insert or update or delete on public.employees for each row execute function public.audit_row();
create trigger audit after insert or update or delete on public.payroll_entries for each row execute function public.audit_row();
create trigger audit after insert or update or delete on public.app_users for each row execute function public.audit_row('email');

-- The app connects with the database owner role (bypasses RLS). RLS with no policies keeps the
-- public Supabase Data API (anon key) from reading or writing any of these tables.
alter table public.audit_log enable row level security;
alter table public.vehicle_classes enable row level security;
alter table public.catalog_items enable row level security;
alter table public.catalog_prices enable row level security;
alter table public.job_items enable row level security;
alter table public.app_users enable row level security;
alter table public.legacy_v1_jobs enable row level security;
alter table public.legacy_v1_services enable row level security;
alter table public.legacy_v1_addons enable row level security;
alter table public.legacy_v1_payroll_entries enable row level security;
