-- 004: payroll by any date range.
--   * attendance: one row per employee per day (code + overtime hours).
--   * payroll_adjustments: dated additions/deductions (cash advance, bonus, ...).
--   * employee_rates: rate history; the rate in effect on a day is used for that day.
--   * payroll_payouts: wages paid out of the drawer (counted in that day's EOD).
-- The weekly sheets (payroll_entries) are converted and kept as legacy_v2_payroll_entries.

create table public.employee_rates (
  employee_id bigint not null references public.employees (id) on delete cascade,
  effective_from date not null,
  rate_per_day numeric(12,2) not null check (rate_per_day >= 0),
  construction_rate numeric(12,2) not null check (construction_rate >= 0),
  primary key (employee_id, effective_from)
);

create table public.attendance (
  employee_id bigint not null references public.employees (id) on delete cascade,
  work_date date not null,
  code text check (code in ('P', '0.5P', 'CN', '0.5CN', 'A', 'OFF')),
  cw_ot_hours numeric(6,2) not null default 0 check (cw_ot_hours >= 0),
  cn_ot_hours numeric(6,2) not null default 0 check (cn_ot_hours >= 0),
  primary key (employee_id, work_date),
  check (code is not null or cw_ot_hours > 0 or cn_ot_hours > 0)
);
create index attendance_work_date_idx on public.attendance (work_date);

create table public.payroll_adjustments (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.employees (id) on delete cascade,
  adj_date date not null,
  kind text not null check (kind in ('addition', 'deduction')),
  amount numeric(12,2) not null check (amount > 0),
  note text not null check (btrim(note) <> ''),
  created_at timestamptz not null default now(),
  created_by text default nullif(current_setting('app.actor', true), '')
);
create index payroll_adjustments_date_idx on public.payroll_adjustments (adj_date);

create table public.payroll_payouts (
  id bigint generated by default as identity primary key,
  payout_date date not null,
  period_start date not null,
  period_end date not null,
  side text not null check (side in ('cash', 'gcash')),
  amount numeric(12,2) not null check (amount > 0),
  note text,
  created_at timestamptz not null default now(),
  created_by text default nullif(current_setting('app.actor', true), ''),
  check (period_start <= period_end)
);
create index payroll_payouts_date_idx on public.payroll_payouts (payout_date);

-- ---------------------------------------------------------------- convert the weekly sheets

-- Rate history: each week's frozen rate, recorded only when it changed. The first known rate
-- applies to all earlier dates.
with points as (
  select employee_id, period_start, rate_per_day, construction_rate,
         lag(rate_per_day) over w as prev_rate, lag(construction_rate) over w as prev_cn,
         row_number() over w as rn
  from public.payroll_entries
  window w as (partition by employee_id order by period_start)
)
insert into public.employee_rates (employee_id, effective_from, rate_per_day, construction_rate)
select employee_id, case when rn = 1 then date '2000-01-01' else period_start end, rate_per_day, construction_rate
from points
where rn = 1 or (rate_per_day, construction_rate) is distinct from (prev_rate, prev_cn);

-- The employee's current rate applies from the week after their last sheet (or always, if none).
insert into public.employee_rates (employee_id, effective_from, rate_per_day, construction_rate)
select e.id, coalesce(latest.period_start + 7, date '2000-01-01'), e.rate_per_day, e.construction_rate
from public.employees e
left join lateral (
  select p.period_start, p.rate_per_day, p.construction_rate from public.payroll_entries p
  where p.employee_id = e.id order by p.period_start desc limit 1
) latest on true
where latest.period_start is null
   or (latest.rate_per_day, latest.construction_rate) is distinct from (e.rate_per_day, e.construction_rate)
on conflict (employee_id, effective_from) do update
  set rate_per_day = excluded.rate_per_day, construction_rate = excluded.construction_rate;

insert into public.attendance (employee_id, work_date, code)
select p.employee_id, a.key::date, a.value
from public.payroll_entries p, jsonb_each_text(p.attendance) a
where a.value in ('P', '0.5P', 'CN', '0.5CN', 'A', 'OFF')
on conflict (employee_id, work_date) do update set code = excluded.code;

-- Weekly overtime is placed on the first day of its week.
insert into public.attendance (employee_id, work_date, cw_ot_hours, cn_ot_hours)
select employee_id, period_start, cw_ot_hours, cn_ot_hours
from public.payroll_entries where cw_ot_hours > 0 or cn_ot_hours > 0
on conflict (employee_id, work_date) do update
  set cw_ot_hours = public.attendance.cw_ot_hours + excluded.cw_ot_hours,
      cn_ot_hours = public.attendance.cn_ot_hours + excluded.cn_ot_hours;

insert into public.payroll_adjustments (employee_id, adj_date, kind, amount, note)
select employee_id, period_start, 'deduction', deductions, coalesce(nullif(btrim(notes), ''), 'Weekly deductions')
from public.payroll_entries where deductions > 0;

drop trigger audit on public.payroll_entries;
drop trigger set_updated_at on public.payroll_entries;
alter table public.payroll_entries rename to legacy_v2_payroll_entries;

alter table public.employees
  drop constraint employees_rates_check,
  drop column rate_per_day,
  drop column construction_rate;

-- ---------------------------------------------------------------- triggers, RLS

create trigger audit after insert or update or delete on public.employee_rates for each row execute function public.audit_row('employee_id');
create trigger audit after insert or update or delete on public.attendance for each row execute function public.audit_row('employee_id');
create trigger audit after insert or update or delete on public.payroll_adjustments for each row execute function public.audit_row();
create trigger audit after insert or update or delete on public.payroll_payouts for each row execute function public.audit_row();

alter table public.employee_rates enable row level security;
alter table public.attendance enable row level security;
alter table public.payroll_adjustments enable row level security;
alter table public.payroll_payouts enable row level security;
