-- 005: bill funds (sinking funds) so big bills never come as a surprise.
--   * funds: one per recurring bill (Meralco, Maynilad, ...), with its usual amount and due date.
--   * fund_set_asides: money taken out of the drawer at EOD into a fund (counted in that day's EOD).
--   * bill_payments: a bill paid from its fund; any shortfall comes from that day's drawer.

create table public.funds (
  id bigint generated by default as identity primary key,
  name text not null check (btrim(name) <> ''),
  amount numeric(12,2) not null default 0 check (amount >= 0),
  frequency text not null check (frequency in ('monthly', 'quarterly', 'yearly')),
  due_day integer not null check (due_day between 1 and 31),
  due_month integer check (due_month between 1 and 12),
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (frequency = 'monthly' or due_month is not null)
);
create unique index funds_active_name_key on public.funds (lower(name)) where active;

-- Amounts and due days are placeholders for the owner to set in Finance.
insert into public.funds (name, frequency, due_day, due_month, sort_order) values
  ('Meralco', 'monthly', 25, null, 10),
  ('Maynilad', 'monthly', 25, null, 20),
  ('Internet', 'monthly', 15, null, 30),
  ('Rent', 'monthly', 1, null, 40),
  ('Business permit', 'yearly', 20, 1, 50);

create table public.fund_set_asides (
  id bigint generated by default as identity primary key,
  fund_id bigint not null references public.funds (id),
  entry_date date not null,
  side text not null check (side in ('cash', 'gcash')),
  amount numeric(12,2) not null check (amount > 0),
  note text,
  created_at timestamptz not null default now(),
  created_by text default nullif(current_setting('app.actor', true), '')
);
create index fund_set_asides_date_idx on public.fund_set_asides (entry_date);
create index fund_set_asides_fund_idx on public.fund_set_asides (fund_id);

create table public.bill_payments (
  id bigint generated by default as identity primary key,
  fund_id bigint not null references public.funds (id),
  paid_on date not null,
  amount numeric(12,2) not null check (amount > 0),
  from_fund numeric(12,2) not null check (from_fund >= 0),
  from_drawer numeric(12,2) not null check (from_drawer >= 0),
  drawer_side text check (drawer_side in ('cash', 'gcash')),
  note text,
  created_at timestamptz not null default now(),
  created_by text default nullif(current_setting('app.actor', true), ''),
  check (amount = from_fund + from_drawer),
  check ((from_drawer = 0) = (drawer_side is null))
);
create index bill_payments_paid_on_idx on public.bill_payments (paid_on);
create index bill_payments_fund_idx on public.bill_payments (fund_id);

create trigger set_updated_at before update on public.funds for each row execute function public.set_updated_at();
create trigger audit after insert or update or delete on public.funds for each row execute function public.audit_row();
create trigger audit after insert or update or delete on public.fund_set_asides for each row execute function public.audit_row();
create trigger audit after insert or update or delete on public.bill_payments for each row execute function public.audit_row();

alter table public.funds enable row level security;
alter table public.fund_set_asides enable row level security;
alter table public.bill_payments enable row level security;
