-- 006: car parts inventory.
--   * parts: price list + stock (never below zero) + weighted average cost.
--   * stock_movements: every receive / sale / return / adjustment, so stock can always be traced.
--   * job_items gain part lines (part_id, quantity, frozen unit_cost) so parts can be sold on any job.
--   * a "parts" department for over-the-counter sales (same-day like carwash, no vehicle needed).

create table public.parts (
  id bigint generated by default as identity primary key,
  sku text check (sku is null or btrim(sku) <> ''),
  name text not null check (btrim(name) <> ''),
  unit text not null default 'pc' check (btrim(unit) <> ''),
  price numeric(12,2) not null default 0 check (price >= 0),
  commission numeric(12,2) not null default 0 check (commission >= 0),
  avg_cost numeric(12,2) not null default 0 check (avg_cost >= 0),
  stock numeric(12,2) not null default 0 check (stock >= 0),
  reorder_level numeric(12,2) not null default 0 check (reorder_level >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index parts_active_sku_key on public.parts (lower(sku)) where active and sku is not null;
create unique index parts_active_name_key on public.parts (lower(name)) where active;

create table public.stock_movements (
  id bigint generated by default as identity primary key,
  part_id bigint not null references public.parts (id),
  moved_on date not null,
  kind text not null check (kind in ('receive', 'sale', 'return', 'adjust')),
  quantity numeric(12,2) not null check (quantity <> 0),
  unit_cost numeric(12,2) check (unit_cost >= 0),
  job_id bigint references public.jobs (id) on delete set null,
  supplier text,
  note text,
  created_at timestamptz not null default now(),
  created_by text default nullif(current_setting('app.actor', true), ''),
  check ((kind in ('receive', 'return') and quantity > 0) or (kind = 'sale' and quantity < 0) or kind = 'adjust')
);
create index stock_movements_part_idx on public.stock_movements (part_id, id);

alter table public.job_items
  drop constraint job_items_kind_check,
  add constraint job_items_kind_check check (kind in ('service', 'addon', 'custom', 'part')),
  add column part_id bigint references public.parts (id),
  add column quantity numeric(12,2) not null default 1 check (quantity > 0),
  add column unit_cost numeric(12,2) check (unit_cost >= 0),
  add constraint job_items_part_check check (kind <> 'part' or part_id is not null);

-- ---------------------------------------------------------------- parts counter department

drop index public.jobs_sale_date_idx;
drop index public.jobs_active_running_idx;
alter table public.jobs
  drop constraint jobs_department_check,
  drop constraint jobs_running_dates_check,
  drop column sale_date;

alter table public.jobs
  add column sale_date date generated always as (
    case
      when department in ('carwash', 'parts') then job_date
      when closed_on is not null and paid_on is not null then greatest(closed_on, paid_on)
    end
  ) stored,
  add constraint jobs_department_check check (department in ('carwash', 'detailing', 'tint_ppf', 'parts')),
  add constraint jobs_running_dates_check check (
    (department in ('carwash', 'parts') and closed_on is null and paid_on is null)
    or (department in ('detailing', 'tint_ppf')
        and payment_received = (paid_on is not null)
        and (closed_on is null or closed_on >= job_date)
        and (paid_on is null or paid_on >= job_date))
  );
create index jobs_sale_date_idx on public.jobs (sale_date);
create index jobs_active_running_idx on public.jobs (department) where sale_date is null and voided_at is null;

create trigger set_updated_at before update on public.parts for each row execute function public.set_updated_at();
create trigger audit after insert or update or delete on public.parts for each row execute function public.audit_row();
create trigger audit after insert or update or delete on public.stock_movements for each row execute function public.audit_row();

alter table public.parts enable row level security;
alter table public.stock_movements enable row level security;
