-- 008: the cash fund (revolving fund) for abonos: purchases the day's sales cannot cover yet.
--   * cash_fund: one row holding the fund's size (the owner sets it; 0 until then).
--   * cash_fund_topups: money the boss hands over: the starting amount and each replenishment.
--   * expenses.side 'fund': a purchase paid from the cash fund. It is a cost of that day but never
--     touches the drawer. expenses.topup_id links it to the replenishment that paid it back
--     (null = still waiting to be replenished).
-- Existing expenses are unchanged (all are cash/GCash, none linked).

create table public.cash_fund (
  id integer primary key default 1 check (id = 1),
  target numeric(12,2) not null default 0 check (target >= 0),
  updated_at timestamptz not null default now()
);
insert into public.cash_fund (id, target) values (1, 0);

create table public.cash_fund_topups (
  id bigint generated by default as identity primary key,
  entry_date date not null,
  amount numeric(12,2) not null check (amount > 0),
  note text,
  created_at timestamptz not null default now(),
  created_by text default nullif(current_setting('app.actor', true), '')
);
create index cash_fund_topups_date_idx on public.cash_fund_topups (entry_date);

alter table public.expenses drop constraint expenses_side_check;
alter table public.expenses add constraint expenses_side_check check (side in ('cash', 'gcash', 'fund'));
alter table public.expenses add column topup_id bigint references public.cash_fund_topups (id) on delete set null;
alter table public.expenses add constraint expenses_topup_fund_check check (topup_id is null or side = 'fund');
create index expenses_topup_idx on public.expenses (topup_id) where side = 'fund';

create trigger set_updated_at before update on public.cash_fund for each row execute function public.set_updated_at();
create trigger audit after insert or update or delete on public.cash_fund for each row execute function public.audit_row();
create trigger audit after insert or update or delete on public.cash_fund_topups for each row execute function public.audit_row();

alter table public.cash_fund enable row level security;
alter table public.cash_fund_topups enable row level security;
