-- GM QA database schema for Supabase/Postgres.
-- Run this once in Supabase Dashboard -> SQL Editor.

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  name text unique not null,
  "price_S" numeric default 0,
  "price_M" numeric default 0,
  "price_L" numeric default 0,
  "price_XL" numeric default 0,
  "price_MOTO" numeric default 0,
  "price_BIG_MOTO" numeric default 0,
  "comm_S" numeric default 0,
  "comm_M" numeric default 0,
  "comm_L" numeric default 0,
  "comm_XL" numeric default 0,
  "comm_MOTO" numeric default 0,
  "comm_BIG_MOTO" numeric default 0,
  is_custom integer default 0,
  active integer default 1
);

create table if not exists public.addons (
  id bigint generated by default as identity primary key,
  name text unique not null,
  "price_S" numeric default 0,
  "price_M" numeric default 0,
  "price_L" numeric default 0,
  "price_XL" numeric default 0,
  "price_MOTO" numeric default 0,
  "price_BIG_MOTO" numeric default 0,
  "comm_S" numeric default 0,
  "comm_M" numeric default 0,
  "comm_L" numeric default 0,
  "comm_XL" numeric default 0,
  "comm_MOTO" numeric default 0,
  "comm_BIG_MOTO" numeric default 0,
  active integer default 1
);

create table if not exists public.jobs (
  id bigint generated by default as identity primary key,
  jo_number text,
  job_date text not null,
  time_in text,
  time_out text,
  vehicle_class text,
  plate text,
  service_id bigint references public.services(id),
  addon_id bigint references public.addons(id),
  addon_price_override numeric,
  custom_addon_name text,
  custom_price numeric default 0,
  custom_comm numeric default 0,
  discount numeric default 0,
  discount_reason text,
  tip_gcash numeric default 0,
  payment_method text default 'Cash',
  payment_received integer default 1,
  commission_paid integer default 1,
  commission_payment_method text default 'Cash',
  commission_cash_paid numeric,
  commission_gcash_paid numeric,
  detailer text,
  remarks text,
  created_at timestamptz default now()
);

create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  expense_date text not null,
  side text not null,
  description text,
  amount numeric default 0
);

create table if not exists public.daily_meta (
  job_date text primary key,
  supervisor text,
  cash_float numeric default 0,
  actual_cash numeric,
  actual_gcash numeric,
  gcash_tips_to_distribute numeric default 0
);

create table if not exists public.employees (
  id bigint generated by default as identity primary key,
  name text unique not null,
  role text default '',
  rate_per_day numeric default 0,
  construction_rate numeric default 700,
  active integer default 1
);

create table if not exists public.payroll_entries (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.employees(id),
  period_label text not null,
  attendance text default '{}',
  days_worked numeric default 0,
  half_days numeric default 0,
  absences numeric default 0,
  day_off integer default 0,
  ot_hours numeric default 0,
  cw_ot_hours numeric default 0,
  cn_ot_hours numeric default 0,
  construction_days numeric default 0,
  deductions numeric default 0,
  notes text,
  unique (employee_id, period_label)
);

alter table public.jobs add column if not exists commission_paid integer default 1;
alter table public.jobs add column if not exists payment_received integer default 1;
alter table public.jobs add column if not exists commission_payment_method text default 'Cash';
alter table public.jobs add column if not exists commission_cash_paid numeric;
alter table public.jobs add column if not exists commission_gcash_paid numeric;

create index if not exists jobs_job_date_idx on public.jobs(job_date);
create index if not exists jobs_service_idx on public.jobs(service_id);
create index if not exists jobs_addon_idx on public.jobs(addon_id);
create index if not exists jobs_commission_paid_idx on public.jobs(commission_paid);
create index if not exists jobs_payment_received_idx on public.jobs(payment_received);
create index if not exists expenses_expense_date_idx on public.expenses(expense_date);
create index if not exists payroll_entries_period_idx on public.payroll_entries(period_label);

-- The application API will use the server-only Supabase service-role key.
-- RLS is enabled so accidental browser access cannot read financial data.
alter table public.services enable row level security;
alter table public.addons enable row level security;
alter table public.jobs enable row level security;
alter table public.expenses enable row level security;
alter table public.daily_meta enable row level security;
alter table public.employees enable row level security;
alter table public.payroll_entries enable row level security;